{% set version = '1.6.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-protoclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/protoclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/protoclust/protoclust_{{ version }}.tar.gz
  sha256: 4177a045dcfefabb842b11cf7d23c503fdd4d807877e1677f9440ad6ba4c7431

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('protoclust')"           # [not win]
    - "\"%R%\" -e \"library('protoclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=protoclust
  license: GPL-2.0-only
  summary: Performs minimax linkage hierarchical clustering.  Every cluster has an associated
    prototype element that represents that cluster as described in Bien, J., and Tibshirani,
    R. (2011), "Hierarchical Clustering with Prototypes via Minimax Linkage," The Journal
    of the American Statistical Association, 106(495), 1075-1084.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dlaehnemann

# Package: protoclust
# Type: Package
# Title: Hierarchical Clustering with Prototypes
# Version: 1.6.4
# Date: 2022-03-31
# Author: Jacob Bien and Rob Tibshirani
# Maintainer: Jacob Bien <jbien@usc.edu>
# Description: Performs minimax linkage hierarchical clustering.  Every cluster has an associated prototype element that represents that cluster as described in Bien, J., and Tibshirani, R. (2011), "Hierarchical Clustering with Prototypes via Minimax Linkage," The Journal of the American Statistical Association, 106(495), 1075-1084.
# License: GPL-2
# LazyLoad: yes
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# NeedsCompilation: yes
# Packaged: 2022-04-01 02:35:15 UTC; jacobbien
# Repository: CRAN
# Date/Publication: 2022-04-01 03:20:02 UTC
